enableTmpEmptyDir: true
namespace: tento

global:
  storageClass: local-path

image:
  registry: docker.io
  ## Bitnami MongoDB image name
  repository: bitnami/mongodb
  tag: 5.0.14-debian-11-r0
  pullPolicy: IfNotPresent
  # pullSecrets:
  #   - myRegistryKeySecretName

auth:
  existingSecret: tento-secret
  usernames:
    - "devUser"
#  passwords:
#    - ""
  databases:
    - "tento-local"
